todolist/task/urls.py
from django.urls import path
from .views import (    
                        SignUpCreateView,TaskListView,TaskCreateview,
                        TaskDetailview, TaskUpdateView, TaskDeleteView,
                        HomeView, TaskApiList, TaskApiDetail, TaskCreateAPI
                    )
            

app_name = 'task'

urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('signup/',SignUpCreateView.as_view(),name='signup'),
    path('list_task',TaskListView.as_view(),name='list_task'),
    path('create_task/',TaskCreateview.as_view(),name='create_task'),
    path('detail_task/<int:pk>',TaskDetailview.as_view(),name='detail_task'),
    path('update_task/<int:pk>',TaskUpdateView.as_view(),name='update_task'),
    path('delete_task/<int:pk>',TaskDeleteView.as_view(),name='delete_task'),

    path('api/list', TaskApiList.as_view(), name='api-list'),
    path('api/detail/<int:pk>/', TaskApiDetail.as_view(), name='api-detail'),
    path('api/create', TaskCreateAPI.as_view(), name='api-create'),
]

todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('notadmin/', admin.site.urls),
    path('',include('task.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

todolist/task/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):

    title = models.CharField(max_length=100)
    text =  models.TextField()
    is_done = models.BooleanField(default=False)  
    date_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date_created']

    def __str__(self):
        return self.title
    

todolist/task/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import ( 
                                    CreateView, ListView, DetailView, 
                                    UpdateView, DeleteView, TemplateView
                                )
from .models import Task
from django.contrib.auth.mixins import LoginRequiredMixin 

from .serializers import TaskSerializer
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from .permissions import IsOwner
# Create your views here.





class HomeView(TemplateView):
    template_name = 'task/index.html'


class SignUpCreateView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')

    template_name = 'registration/signup.html'


class TaskCreateview(LoginRequiredMixin,CreateView):           # templat = > task_form.html
    model = Task
    fields = ['title','text']

    success_url = reverse_lazy('task:list_task')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class TaskListView(LoginRequiredMixin,ListView):   
    model = Task
    template_name = 'task/task_list.html'
    paginate_by = 10
    context_object_name = 'task_list'
    def get_queryset(self):

        queryset = Task.objects.filter(user=self.request.user)  
        status_filter = self.request.GET.get('status')
        print(status_filter)
        if status_filter:
            if status_filter=='completed':
                queryset = queryset.filter(user=self.request.user, is_done=True)
            elif status_filter=='pending':
                queryset = queryset.filter(user=self.request.user, is_done=False)


        return queryset


class TaskDetailview(LoginRequiredMixin,DetailView):           # tempalte = > task_detail.html
    model = Task


class TaskUpdateView(LoginRequiredMixin,UpdateView):          
    model = Task
    template_name = 'task/task_update.html'
    fields = ['title', 'text','is_done']
    success_url = reverse_lazy('task:list_task')

class TaskDeleteView(LoginRequiredMixin,DeleteView):
    model = Task
    template_name = 'task/task_confirm_delete.html'
    success_url = reverse_lazy('task:list_task')


# API 

class TaskApiList(generics.ListAPIView):
    serializer_class = TaskSerializer
    permission_classes = [IsAuthenticated, IsOwner]
    def get_queryset(self):

        queryset = Task.objects.filter(user=self.request.user)  
        return queryset


class TaskApiDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    permission_classes = [IsAuthenticated, IsOwner]


class TaskCreateAPI(generics.CreateAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    permission_classes = [IsAuthenticated]
    def perform_create(self, serializer):
            serializer.save(user=self.request.user)

todolist/task/templates/task/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title>ToDo List</title>
      
      <link rel="stylesheet" type="text/css" href="{% static 'task/styles01.css' %}"/>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
   </head>
   <!-- body -->
   <body>
      

      <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
         <div class="container-fluid">
         <a class="navbar-brand" href='{% url "task:home" %}'>ToDo List</a>
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
               <li class="nav-item">
               <a class="nav-link active" aria-current="page" href=' {% url "task:create_task" %} '>Add task</a>
               </li>
               <li class="nav-item">
               <a class="nav-link active" href=' {% url "task:list_task" %} '>List</a>
               </li>
               {% if user.is_authenticated %}

                  <li class="nav-item">
                     <form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="nav-link active">logout</button>
                     </form>
                  </li>           
               {% else %}
                  <li class="nav-item ">
                     <a class="nav-link active" href=' {% url "login" %} '>LogIn</a>
                  </li>
                  <li class="nav-item ">
                     <a class="nav-link active" href=' {% url "task:signup" %} '>SignIn</a>
                  </li>
                                   
               {% endif %}
            </ul>
         </div>
         </div>
      </nav>
 
 
      {% block content %}
      {% endblock content %}
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
   </body>
</html>

todolist/task/templates/task/index.html
{% extends "task/base.html" %}
{% load static %}


{% block content %}
<div class="top-home">
    <h1>ToDo List Manager</h1>
    <h2>Let's Start</h2>
    
    {% if user.is_authenticated %}
    <div class="buttons">
      <a  href=' {% url "task:list_task" %} '><button class="btn btn-primary">Task List</button></a>
   </div>    
 {% else %}
 <div class="buttons">
   <a  href=' {% url "login" %} '><button class="btn btn-primary">Login</button></a>
       <a  href=' {% url "task:signup" %} '><button class="btn btn-primary">Signin</button></a>
</div>
                     
 {% endif %}
    
</div>
{% endblock content %}

todolist/task/templates/task/task_confirm_delete.html
{% extends "task/base.html" %}
{% load static %}


{% block content %}

{% if task.user != user %}      {% comment %} checks if the user is the same one that made the post {% endcomment %}
    
    <p class="error"> You dont have permission for this page</p>
{% else %}

<div class="top">
    <div class='wrapper'>
        <form method='POST'>
            {% csrf_token %}
        <h3>Are you sure you want to delete this task?</h3>
        <hr style="background:#046c58;">
        <h4>Title : <b><i>{{task.title}}</i></b></h4>  
        
            <div class='post-btns'>
                <input class='btn btn-danger up-btn btn-lg' type='submit' value='delete'>
            </div>
        </form>
    </div>
</div>

{% endif %}
{% endblock content %}

todolist/task/templates/task/task_detail.html
{% extends "task/base.html" %}
{% load static %}


{% block content %}

{% if task.user != user %}      {% comment %} checks if the user is the same one that made the post {% endcomment %}
    
    <p class="p-3 mb-2 bg-danger text-white"> You dont have permission for this page</p>
{% else %}

<div class="top">
        <div class='wrapper'>    
                        <div class="row">
                            <div class="input-box ">
                                <label class="form-label">Title</label>
                                <input class="form_control" placeholder="Title " type="text" name="title" value="{{task.title}}" disabled>
                            </div>
                            <div>
                                <label class="form-label">{{task.date_created}}</label>
                            </div>
                            <div class="input-box">
                                <label class="form-label">Text</label>
                                <textarea class="textarea" placeholder="Text" type="text" name="text" disabled>{{task.text}}</textarea>
                            </div>
                            <div class="mycheckbox">
                                <div class='register-link'>
                                    <label for="is_done" class='form-checkbox-label'> is done?</label>
                                    <input type="checkbox" id="is_done" name="is_done" {% if task.is_done %}checked{% endif %} disabled/>  
                                </div>
                            </div>
                        <div class='btn-group btn-group-lg text-center' role="group">
                            <a  href='/update_task/{{task.id}}'><button class='btn btn-primary up-btn btn-lg'>Update</button></a>
                            <a  href='/delete_task/{{task.id}}'><button class='btn btn-danger up-btn btn-lg'>Delete</button></a>
                            <a  href='{% url "task:list_task" %}'><button class='btn btn-success up-btn btn-lg'>Back</button></a>
                         </div>            
        </div>

        
    </div>
{% endif %}

{% endblock content %}

todolist/task/templates/task/task_form.html
{% extends "task/base.html" %}
{% load static %}


{% block content %}
<div class="top">
            <div class="wrapper">
                <form class="main_form " method='POST'>
                    {% csrf_token %}
                    <h1>Add new task</h1>
                    <div class="row">
                        <div class="input-box ">
                            <label class="form-label">Title</label>
                            <input class="form_control" placeholder="Title " type="text" name="title">
                            {% for err in form.text.errors %}
                                <small class='text-danger'>{{err}}</small>
                            {% endfor %}
                        </div>
                        <div class="input-box">
                            <label class="form-label">Text</label>
                            <textarea class="textarea" placeholder="Text" type="text" name="text"></textarea>
                            {% for err in form.text.errors %}
                                <small class='text-danger'>{{err}}</small>
                            {% endfor %}
                        </div>
                        <div class="col-sm-12 post-btn">
                            <button class="btn btn-primary">Post</button>
                        </div>
                    </div>
                </form>
           
</div>
{% endblock content %}

todolist/task/templates/task/task_list.html
{% extends "task/base.html" %}
{% load static %}


{% block content %}
<div class="top">
   <div class="wrapper">
      <div class="row">
         <h1>List Of Tasks</h1>
         <form method="GET">
            <label for="is_done">Filter by Status:</label>
            <select name="status" id="status">
               <option value="">All</option>
               <option value="pending">Pending</option>
               <option value="completed">Completed</option>
            </select>

            <button class='btn-primary' type="submit">Apply Filter</button>
         </form>

         <div class="card" style="width: 18rem;">
            
            <ul class="list-group list-group-flush">
               {% for task in task_list %}
               <li class="list-group-item"><a href='/detail_task/{{task.id}}' class='post-btn'>{{task.title}}</a></li>
            {% endfor %}
            </ul>
         </div>
         

         <nav aria-label="...">
            <ul class="pagination">
               {% if page_obj.has_previous %}
                  <li class="page-item"><a class="page-link" href="?page=1">&laquo;first</a></li>
                  <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
                  <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
               {% endif %}
            
            
            <li class="page-item active">
               <a class="page-link" href="#" aria-current="page">{{ page_obj.number }}</a>
            </li>
            
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a></li>
            {% endif %}
            </ul>
         </nav>
 
      </div>
   </div>
</div>
{% endblock content %}

todolist/task/templates/task/task_update.html
{% extends "task/base.html" %}
{% load static %}


{% block content %}

{% if task.user != user %}      {% comment %} checks if the user is the same one that made the post {% endcomment %}
    
    <p class="p-3 mb-2 bg-danger text-white"> You dont have permission for this page</p>
{% else %}
<div class="top">
    <div class="wrapper">
                    <form class="main_form " method='POST'>
                        {% csrf_token %}
                        <h1>Edit Task</h1>
                        <div class="row">
                            
                            <div class="input-box ">
                                <label class="form-label">Title</label>
                                <input class="form_control" placeholder="Title " type="text" name="title" value="{{ form.title.value }}">
                                {% for err in form.text.errors %}
                                    <small class='text-danger'>{{err}}</small>
                                {% endfor %}
                            </div>

                            <div class="input-box">
                                <label class="form-label">Text</label>
                                <textarea class="textarea" placeholder="Text" type="text" name="text">{{ form.text.value }}</textarea>
                                {% for err in form.text.errors %}
                                    <small class='text-danger'>{{err}}</small>
                                {% endfor %}
                            </div>


                            <div class="mycheckbox">
                                <div class='register-link'>
                                    <label for="is_done" class='form-checkbox-label'> is done?</label>
                                    <input type="checkbox" id="is_done" name="is_done" {% if form.is_done.value %}checked{% endif %} />  
                                </div>
                            </div>
                    


                            <div class="col-sm-12">
                                <button class="btn btn-primary post-btn">Save</button>
                            </div>
                        </div>
                    </form>
                </div>         
</div>
{% endif %}
{% endblock content %}